name: Tests

on: 
  workflow_dispatch:
  push: 
    paths-ignore: 
      - 'docs/**'
      - '.vscode'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 16, 17]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Run Tests
      run: |
        npm install -ci
        npm run test:ci